#ifndef _H_TESTA_SM
#define _H_TESTA_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : testA_sm.sm
 */


#include <statemap.h>

namespace ProdA
{
    // Forward declarations.
    class prod;
    class prod_Inside;
    class prod_InsideState2;
    class prod_Default;
    class common;
    class common_Init;
    class common_InsideSubmap;
    class common_Finish;
    class common_Default;
    class TestAState;
    class testAContext;
    class TestA;

    class TestAState :
        public statemap::State
    {
    public:

        TestAState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(testAContext&) {};
        virtual void Exit(testAContext&) {};

        virtual void backToInit(testAContext& context);
        virtual void goBack(testAContext& context);
        virtual void goInside(testAContext& context);
        virtual void goState2(testAContext& context);
        virtual void leaveInit(testAContext& context);

    protected:

        virtual void Default(testAContext& context);
    };

    class prod
    {
    public:

        static prod_Inside Inside;
        static prod_InsideState2 InsideState2;
    };

    class prod_Default :
        public TestAState
    {
    public:

        prod_Default(const char *name, int stateId)
        : TestAState(name, stateId)
        {};

        virtual void goBack(testAContext& context);
    };

    class prod_Inside :
        public prod_Default
    {
    public:
        prod_Inside(const char *name, int stateId)
        : prod_Default(name, stateId)
        {};

        void goState2(testAContext& context);
    };

    class prod_InsideState2 :
        public prod_Default
    {
    public:
        prod_InsideState2(const char *name, int stateId)
        : prod_Default(name, stateId)
        {};

    };

    class common
    {
    public:

        static common_Init Init;
        static common_InsideSubmap InsideSubmap;
        static common_Finish Finish;
    };

    class common_Default :
        public TestAState
    {
    public:

        common_Default(const char *name, int stateId)
        : TestAState(name, stateId)
        {};

    };

    class common_Init :
        public common_Default
    {
    public:
        common_Init(const char *name, int stateId)
        : common_Default(name, stateId)
        {};

        void Entry(testAContext&);
        void Exit(testAContext&);
        void goInside(testAContext& context);
        void leaveInit(testAContext& context);
    };

    class common_InsideSubmap :
        public common_Default
    {
    public:
        common_InsideSubmap(const char *name, int stateId)
        : common_Default(name, stateId)
        {};

        void Entry(testAContext&);
        void Exit(testAContext&);
    };

    class common_Finish :
        public common_Default
    {
    public:
        common_Finish(const char *name, int stateId)
        : common_Default(name, stateId)
        {};

        void backToInit(testAContext& context);
    };

    class testAContext :
        public statemap::FSMContext
    {
    public:

        testAContext(TestA& owner)
        : FSMContext(common::Init),
          _owner(owner)
        {};

        testAContext(TestA& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        TestA& getOwner() const
        {
            return (_owner);
        };

        TestAState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<TestAState&>(*_state));
        };

        void backToInit()
        {
            setTransition("backToInit");
            (getState()).backToInit(*this);
            setTransition(NULL);
        };

        void goBack()
        {
            setTransition("goBack");
            (getState()).goBack(*this);
            setTransition(NULL);
        };

        void goInside()
        {
            setTransition("goInside");
            (getState()).goInside(*this);
            setTransition(NULL);
        };

        void goState2()
        {
            setTransition("goState2");
            (getState()).goState2(*this);
            setTransition(NULL);
        };

        void leaveInit()
        {
            setTransition("leaveInit");
            (getState()).leaveInit(*this);
            setTransition(NULL);
        };

    private:

        TestA& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_TESTA_SM
